-- WARNING: Backup your database before running this script!
-- This script assumes your table is named 'Categories' and the column 'CategoryID'.

PRINT 'Starting script to change Categories.CategoryID to INT IDENTITY PRIMARY KEY.';
PRINT '--------------------------------------------------------------------------';

-- Step 1: Identify and drop existing Primary Key constraint on CategoryID (if it's the PK)
PRINT 'Step 1: Dropping existing Primary Key constraint on CategoryID if it exists...';
IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS T
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS K ON T.CONSTRAINT_NAME = K.CONSTRAINT_NAME
    WHERE T.TABLE_NAME = 'Categories' AND K.COLUMN_NAME = 'CategoryID' AND T.CONSTRAINT_TYPE = 'PRIMARY KEY'
)
BEGIN
    DECLARE @ConstraintName NVARCHAR(255);
    SELECT @ConstraintName = K.CONSTRAINT_NAME
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS T
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS K ON T.CONSTRAINT_NAME = K.CONSTRAINT_NAME
    WHERE T.TABLE_NAME = 'Categories' AND K.COLUMN_NAME = 'CategoryID' AND T.CONSTRAINT_TYPE = 'PRIMARY KEY';

    IF @ConstraintName IS NOT NULL
    BEGIN
        EXEC('ALTER TABLE Categories DROP CONSTRAINT [' + @ConstraintName + '];');
        PRINT 'Dropped existing Primary Key constraint: [' + @ConstraintName + '] on CategoryID.';
    END
    ELSE
    BEGIN
        PRINT 'No existing Primary Key constraint found on CategoryID to drop.';
    END
END
ELSE
BEGIN
    PRINT 'No Primary Key constraint metadata found for Categories.CategoryID.';
END
PRINT '--------------------------------------------------------------------------';
GO

-- Step 2: Drop any foreign key constraints that reference Categories.CategoryID
PRINT 'Step 2: Manual intervention required for Foreign Keys.';
PRINT 'INFO: If other tables have Foreign Keys referencing Categories.CategoryID, those FK constraints must be dropped now before proceeding.';
PRINT 'Example: -- ALTER TABLE YourOtherTable DROP CONSTRAINT FK_YourConstraintName;';
PRINT 'Please execute these DROP FK commands manually if they exist.';
PRINT 'The script will pause for 10 seconds to allow you to do this if necessary.';
PRINT '--------------------------------------------------------------------------';
WAITFOR DELAY '00:00:10'; -- Pause to allow manual intervention if needed
GO

-- Step 3: Create a new table with the desired schema (INT IDENTITY PK)
PRINT 'Step 3: Creating Categories_New table with CategoryID INT IDENTITY(1,1) PRIMARY KEY...';
CREATE TABLE Categories_New (
    CategoryID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL, -- Ensure this matches your existing Name column type and nullability
    Photo NVARCHAR(500) NULL     -- Ensure this matches your existing Photo column type and nullability
);
PRINT 'Created Categories_New table.';
PRINT '--------------------------------------------------------------------------';
GO

-- Step 4: Copy data from the old table to the new table
PRINT 'Step 4: Copying data from Categories to Categories_New...';
-- This assumes new CategoryIDs will be generated by IDENTITY.
INSERT INTO Categories_New (Name, Photo)
SELECT Name, Photo
FROM Categories;
PRINT 'Copied data from Categories to Categories_New. New CategoryIDs were generated.';
PRINT '--------------------------------------------------------------------------';
GO

-- Step 5: Drop the old Categories table
PRINT 'Step 5: Dropping old Categories table...';
DROP TABLE Categories;
PRINT 'Dropped old Categories table.';
PRINT '--------------------------------------------------------------------------';
GO

-- Step 6: Rename the new table to Categories
PRINT 'Step 6: Renaming Categories_New to Categories...';
EXEC sp_rename 'Categories_New', 'Categories';
PRINT 'Renamed Categories_New to Categories.';
PRINT '--------------------------------------------------------------------------';
GO

-- Step 7: Recreate any foreign key constraints that were dropped in Step 2
PRINT 'Step 7: Manual intervention required for Foreign Keys.';
PRINT 'INFO: Recreate any Foreign Key constraints that previously referenced the old Categories.CategoryID, now pointing to the new INT CategoryID.';
PRINT 'Example: -- ALTER TABLE YourOtherTable ADD CONSTRAINT FK_YourConstraintName FOREIGN KEY (YourForeignKeyColumn) REFERENCES Categories(CategoryID);';
PRINT 'Please execute these ADD FK commands manually if they were dropped earlier.';
PRINT '--------------------------------------------------------------------------';
GO

PRINT 'Script finished. The Categories table should now have CategoryID as INT IDENTITY(1,1) PRIMARY KEY.';
PRINT 'Please verify the changes and your foreign key constraints.';